language: java
branches:
  only:
    - developer
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - antonio@gonzalez.cr
script:
    - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify