language: java
branches: 
  only:
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - antonio@gonzalez.cr
script:
   #Commentario sobre segundo intento
    - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
    #SONARCLOUD
    - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=antgonto -Dsonar.login=$SONAR -Dsonar.branch.name=developer
deploy:
  provider: heroku
  api_key:
    secure: 3ee5d341-41e4-4c84-afbb-dcc81e384974
  on:
    branch: master
  app: ecosystem-demo-antonio